### ISSUE TITLE
Where can i find the document for this?

### ISSUE THREAD

**Issue by stunievi** [knilink/react-jsonschema-formbuilder#2]

**Comment by MedinaGitHub** [comment]
HI, this proyect works?

**Comment by knilink** [comment]
Hi @MedinaGitHub,
Thank you for expressing your interest in this project. 
I've just checked the project and it's still working as expected. 
If you are experiencing some `Invalid prop`  validation warning. That might be related to this issue. https://github.com/rjsf-team/react-jsonschema-form/issues/1309

**Comment by MedinaGitHub** [comment]
Yes, it is running on my localhost, thanks. Do you use this project yet? or use another solution?
I have also tried this solution https://redgeoff.github.io/mson-react/form-builder, do you know MSON?

**Comment by MedinaGitHub** [comment]
it project is on npm ?

**Comment by knilink** [comment]
@MedinaGitHub The form build for now is just an application not a module so is not published on npm. Currently, I don't have plans to make it an npm module because it's heavily rely on 3rd party ui library `antd`.
